### ISSUE TITLE
CT abdomen image segmentation is not good

### ISSUE THREAD

**Issue by jianjun0407** [openmedlab/MedLSAM#7]
Thank you for sharing. I tried to perform the task of abdomen segmentation directly on CT images, but the results were not good. The following is my result map, please ask what the possible reasons are?
![Abdomen_medlam_img0001_0_cl7](https://github.com/openmedlab/MedLSAM/assets/19251556/e145f3d6-445c-4894-9388-fe4aa76835d0)
![Abdomen_medlam_img0002_0_cl1](https://github.com/openmedlab/MedLSAM/assets/19251556/6a2e82b2-fe8d-4a93-a22d-da4cdf1c3006)
![捕获](https://github.com/openmedlab/MedLSAM/assets/19251556/0a9d5223-5ddc-4a1d-a83a-f22366a4abed)

**Comment by lingling-7-7** [comment]
Hello, may I ask how you used this dataset for inference? I also use the same dataset, but it will report errors, such as inconsistent shapes. What other modifications did you make during inference? Thank you.

I think the reason why his abdominal CT results are not good is that the checkpoint is based on what seems to be brain training, so the categories are not quite the same.

![Uploading 86012301663e5c8e4b23295c487af83.jpg…]()

**Comment by lingling-7-7** [comment]
#### start to preprocess support volume #### 
 
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:22&lt;00:00,  7.57s/it]

 #### start to extract support feature for each class #### 

  0%|                                                                                                                                | 0/13 [00:00&lt;?, ?it/s][29, 41, 19]
[29, 41, 19]
  0%|                                                                                                                                | 0/13 [00:03&lt;?, ?it/s]
Traceback (most recent call last):
  File "/root/data/lingling/MedLSAM-main/MedLAM_Inference.py", line 34, in &lt;module&gt;
    ana_det = AnatomyDetection(args.config_file)
  File "/root/data/lingling/MedLSAM-main/MedLAM/Anatomy_detection.py", line 74, in __init__
    self.RD=process_support(self.RD, support_image_ls, support_label_ls, self.patch_size, \
  File "/root/data/lingling/MedLSAM-main/MedLAM/Cal_support_feature.py", line 54, in process_support
    support_image_batch = np.array(support_image_batch)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 4 dimensions. The detected shape was (36, 1, 64, 64) + inhomogeneous part.

**Comment by lingling-7-7** [comment]
May I ask if your problem has been resolved? My reasoning result on abdominal CT is also the same.
